### PR TITLE
Upgrade to Koa 2 

### PR DESCRIPTION
**Pull request by meaku**
Hey @samora,

I updated the jSend middleware to work with koa2. Many koa-middlewares maintain a master and 2.x branch. I think it would be fine to just merge into master and release as `2.0.0` to mark a breaking change. Otherwise you could make 2.x master and keep the 1.x branch in case you are planning to support it in the future. 

What do you think?

### CODE REVIEW

**Comment by meaku** [comment]
And I forgot to mention that the version bump to 2.0.0 is not strict semver, but it aligns with koa. Could also be 1.0.0.

**Comment by samora** [comment]
Great PR!

**Comment by samora** [comment]
Published on NPM @meaku.

**Comment by meaku** [comment]
Awesome. Thanks. 👍

**Pull request merged**
